DataAccessDemo/DataAccessDemo/Models/RoleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DataAccessDemo.Models
{
    public class RoleModel
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings=false)]
        public string Name { get; set; }
    }
}

DataAccessDemo/DataAccessDemo/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DataAccessDemo.Models
{
    public class UserModel
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings=false)]
        public string Name { get; set; }

        public List<RoleModel> Roles { get; set; }
    }
}

DataAccessDemo/DataAccessDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataAccessDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index ()
        {
            return View();
        }
    }
}

DataAccessDemo/DataAccessDemo/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessDemo.Code;
using DataAccessDemo.Models;

namespace DataAccessDemo.Controllers
{
    public class RoleController : Controller
    {     
        public ActionResult Index()
        {
            var roles = from r in Databases.CreateDatabase().GetRoles()
                        select new RoleModel() { Id = r.Id, Name = r.Name };

            return View(roles);
        }

        public ActionResult Details ( int id )
        {
            var role = Databases.CreateDatabase().GetRole(id);

            return View(new RoleModel() { Id = role.Id, Name = role.Name });
        }

        public ActionResult Edit (int id)
        {
            var role = Databases.CreateDatabase().GetRole(id);

            return View(new RoleModel() { Id = role.Id, Name = role.Name });
        }
    }
}

DataAccessDemo/DataAccessDemo/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessDemo.Code;
using DataAccessDemo.Models;

namespace DataAccessDemo.Controllers
{
    public class UserController : Controller
    {        
        public ActionResult Index()
        {
            var users = from u in Databases.CreateDatabase().GetUsers()
                        select new UserModel() { Id = u.Id, Name = u.Name };

            return View(users);
        }

        public ActionResult Details (int id)
        {
            var user = Databases.CreateDatabase().GetUser(id);

            return View(new UserModel() { Id = user.Id, Name = user.Name });
        }

        public ActionResult Edit (int id)
        {
            var user = Databases.CreateDatabase().GetUser(id);

            return View(new UserModel() { Id = user.Id, Name = user.Name });
        }
    }
}

DataAccessDemo/DataAccessDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Data Access Demo</h1>    
</div>

<div class="row">
    @Html.ActionLink("Manage Users", "Index", "User")
	@Html.ActionLink("Manage Roles", "Index", "Role")
</div>

DataAccessDemo/DataAccessDemo/Views/Role/Details.cshtml
@model DataAccessDemo.Models.RoleModel

@{
    ViewBag.Title = "Get";
}

<h2>Get</h2>

<div>
    <h4>RoleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DataAccessDemo/DataAccessDemo/Views/Role/Edit.cshtml
@model DataAccessDemo.Models.RoleModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RoleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DataAccessDemo/DataAccessDemo/Views/Role/Index.cshtml
@model IEnumerable<DataAccessDemo.Models.RoleModel>

@{
    ViewBag.Title = "Roles";
}

<h2>Roles</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

DataAccessDemo/DataAccessDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Data Access De,p</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Data Access Demo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DataAccessDemo/DataAccessDemo/Views/User/Details.cshtml
@model DataAccessDemo.Models.UserModel

@{
    ViewBag.Title = "Get";
}

<h2>Get</h2>

<div>
    <h4>UserModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DataAccessDemo/DataAccessDemo/Views/User/Edit.cshtml
@model DataAccessDemo.Models.UserModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DataAccessDemo/DataAccessDemo/Views/User/Index.cshtml
@model IEnumerable<DataAccessDemo.Models.UserModel>

@{
    ViewBag.Title = "Manage Users";
}

<h2>Users</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>